#+TITLE: BPF摘录
#+AUTHOR: sqlfocus


本文档摘录linux的BPF实现，了解其原理及实现；在此基础上，了解基于BPF
的过滤技术、动态调试技术。

* 简介
 - BPF  :: Berkeley Packet Filter
 - LSF  :: Linux Socket Filtering

BPF允许用户态程序在任何socket上添加过滤器，以允许或阻断此插口上特定类型
的数据报文；LSF和BPF几乎不二，仅仅是linux发行版上的实现。

* 使用步骤
 - 创建过滤代码
 - 通过SO_ATTACH_FILTER选项传入内核
 - 内核检测代码安全性，开始工作
 - 通过SO_DETACH_FILTER选项撤销过滤器
 - 可通过SO_LOCK_FILTER选项锁定过滤器，防止被移除和修改

* CBPF
沿袭UNIX BPF的指令格式，单条指令固定长度64bits，如下：
 #+BEGIN_EXAMPLE
 struct sock_filter {	/* Filter block */
   __u16  code; /* 指令类型及寻址模型 */
   __u8	  jt;	/* true跳转偏移，相对于下一条指令 */
   __u8	  jf;	/* false跳转偏移 */
   __u32  k;    /* 通用字段，根据code具有不同含义 */
 };
 #+END_EXAMPLE

** 设计原则
 - must be protocol independent
    : 内核不需要修改以支持新协议，packet以byte字符数组呈现
    : 协议相关逻辑固化到过滤器代码
 - must be general
    : 设计成普世模型，提供丰富的指令集，以备未来拓展
 - Packet data references should be minimized
    : 固定的报文字段多次使用时，可加载到寄存器，以减少copy操作
 - Decoding an instruction should consist of a single switch statement
    : 指令内尽量少包含跳转分支数，以提升代码效率
 - abstract machine registers should reside in physical registers
    : 为提升代码性能的考虑

** 指令类型
支持的指令包括load/store/branch/alu/miscellaneous/return等；具体参考
 - ~/include/uapi/linux/bpf_common.h
 - ~/include/uapi/linux/filter.h

** 编译器
内核携带了编译器bpf_asm，~/tools/net/，以抽象指令格式为好理解的汇编语言。
另外编译结果还有bpf_dbg，用于调试汇编代码，具体参考filter.txt。
 #+BEGIN_EXAMPLE
 编译、生成bpf_asm
 $ cd ~/tools/net
 $ sudo apt-get install binutils-dev          引入bfd.h
 $ sudo apt-get install libreadline-dev       引入readline.h
 $ sudo apt-get install bison                 引入bison + flex
 $ sudo apt-get install flex
 $ make
 #+END_EXAMPLE

 #+BEGIN_EXAMPLE
 编译示例BPF汇编
 $ emacs -nw arp.check
     ldh [12]
     jne #0x806, drop
     ret #-1
     drop: ret #0

 $ ./bpf_asm arp.check                生成可直接加载的代码
 $ ./bpf_asm -c arp.check             生成c风格的代码
 #+END_EXAMPLE

* EBPF
不同于CBPF，EBPF是针对linux体系优化后的指令集；即便是CBPF，到linux体系执
行时，在内部也需要先转换为EBPF。

write programs in "restricted C" and compile into eBPF with a optional
GCC/LLVM backend, so that it can just-in-time map to modern 64-bit CPUs 
with minimal performance overhead over two steps, that is, C -> eBPF -> native code.
这是eBPF的设计目标。

 #+BEGIN_EXAMPLE
 struct bpf_insn {
   __u8 code;	   /* 4bits(操作码)/1bit(源)/3bits(指令类型) */
   __u8 dst_reg:4; /* dest register */
   __u8	src_reg:4; /* source register */
   __s16 off;	   /* signed offset */
   __s32 imm;	   /* signed immediate constant */
 };
 #+END_EXAMPLE


** 对比CBPF
 - 寄存器从2增加到10个
    : A/X + 隐藏的frame指针 ==> R0~R9 + 只读frame指针(R10)
    : R0     存放内核函数的返回值，和eBPF的返回值
    : R1-R5  eBPF向内核函数传递参数
    : R6~R9  被调用内核函数的callee saved register
    : R10    只读frame指针，访问堆栈
    :
    : X86_64平台寄存器对应关系
    :     R0 - rax
    :     R1 - rdi
    :     R2 - rsi
    :     R3 - rdx
    :     R4 - rcx
    :     R5 - r8
    :     R6 - rbx
    :     R7 - r13
    :     R8 - r14
    :     R9 - r15
    :     R10- rbp
 - 寄存器宽度由32bit增加到64bit
 - 替换jt/jf为jt/fall-through，减少跳转指令数
 - 引入bpf_call指令，采用硬件相同的寄存器传递惯例，避免额外参数copy开销

** 指令类型
类似于CBPF，支持丰富的指令类型，包括load/store/jmp/alu/alu64等；具体参考
 - include/uapi/linux/bpf.h
 - include/linux/filter.h

** map
映射内存用于eBPF，做为内核程序和用户态程序共享通信的通用存储；此映射区域
由用户态通过bpf()系统调用操控。
 - bpf(BPF_MAP_CREATE,,)            :: 创建map
    : 类型包括hash/array/bloom filter/radix-tree等
 - bpf(BPF_MAP_LOOKUP_ELEM,,)       :: 查找key
 - bpf(BPF_MAP_UPDATE_ELEM,,)       :: 创建和更新key/value
 - bpf(BPF_MAP_DELETE_ELEM,,)       :: 删除key
 - close()                          :: 删除map

** 限制
 - 指令数限制4096
 - 只能同时存在一个ebpf程序
 - eBPF程序第一个参数ctx(R1)是固定的
    : seccomp  -->   seccomp_data
    : BPF      -->   skb

* 汇编示例
内核中预留了bpf的示例代码，路径 ~${linux-src-path}/samples/bpf~ ；可以阅
读此处代码，增加对bpf外围系统的了解。
 #+BEGIN_EXAMPLE
 内核收到的数据报文按类型计数
 $ cd ~/work
 $ cp ${linux-src-path}/samples/bpf/sock_example.c .
 $ cp ${linux-src-path}/samples/bpf/libbpf.* .
 $ gcc sock_example.c libbpf.c
 $ sudo ./a.out
 #+END_EXAMPLE
另外，BCC项目利用ebpf，完善的支持kprobe、uprobe、tracepoint、perf等，可
以参考并加以利用，节省大量的开发。

备注：本人设备上需要屏蔽 ~bpf_create_map()/libbpf.c~ 创建交互内存表函数
的代码 ~.map_flags = map_flags~ ；因为本人设备ubuntu16.04内核版本较拷贝
代码老，对应数据结构没有提供对应字段。

* c语言示例
** 安装clang编译环境
 #+BEGIN_EXAMPLE
 参考http://clang.llvm.org/get_started.html
 
 下载源码包
 ~/Downloads/llvm-4.0.0.src.tar.xz
 ~/Downloads/cfe-4.0.0.src.tar.xz
 ~/Downloads/clang-tools-extra-4.0.0.src.tar.xz
 ~/Downloads/compiler-rt-4.0.0.src.tar.xz

 编译
 $ cd ~/work
 $ tar Jxvf ~/Downloads/llvm-4.0.0.src.tar.xz
 $ tar Jxvf ~/Downloads/cfe-4.0.0.src.tar.xz
 $ mv cfe-4.0.0.src/ llvm-4.0.0.src/tools/
 $ tar Jxvf ~/Downloads/clang-tools-extra-4.0.0.src.tar.xz
 $ mv clang-tools-extra-4.0.0.src/ llvm-4.0.0.src/tools/cfe-4.0.0.src/tools/
 $ tar Jxvf ~/Downloads/compiler-rt-4.0.0.src.tar.xz
 $ mv compiler-rt-4.0.0.src/ llvm-4.0.0.src/projects/
 $ mkdir build
 $ cd build
 $ cmake -G "Unix Makefiles" ../llvm-4.0.0.src/
 $ make
 $ cmake -DCMAKE_INSTALL_PREFIX=/home/sqlfocus/Program/llvm -P cmake_install.cmake

 可执行文件加入搜索路径
 $ emacs -nw ~/.bashrc
     export PATH=$PATH:/home/sqlfocus/Program/llvm/bin
 $ source ~/.bashrc

 验证
 $ clang --help
 #+END_EXAMPLE

** 示例
 #+BEGIN_EXAMPLE
 $ cd ~/work
 $
 $ cp ${linux-src-path}/samples/bpf/bpf_load.c .            #依赖
 $ cp ${linux-src-path}/samples/bpf/bpf_load.h .
 $ cp ${linux-src-path}/samples/bpf/libbpf.c .
 $ cp ${linux-src-path}/samples/bpf/libbpf.h .
 $ cp ${linux-src-path}/samples/bpf/bpf_helpers.h .
 $
 $ cp ${linux-src-path}/samples/bpf/sampleip_user.c .       #应用程序
 $ cp ${linux-src-path}/samples/bpf/sampleip_kern.c .
 $
 $ gcc libbpf.c bpf_load.c sampleip_user.c -o sampleip_user #编译用户态程序
 $
 $ clang  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/include \
        -I/lib/modules/4.10.0-20-generic/build/arch/x86/include \
        -I/lib/modules/4.10.0-20-generic/build/arch/x86/include/generated/uapi \
        -I/lib/modules/4.10.0-20-generic/build/arch/x86/include/generated  \
        -I/lib/modules/4.10.0-20-generic/build/include \
        -I/lib/modules/4.10.0-20-generic/build/arch/x86/include/uapi \
        -I/lib/modules/4.10.0-20-generic/build/include/uapi \
        -I/lib/modules/4.10.0-20-generic/build/include/generated/uapi \
        -include /lib/modules/4.10.0-20-generic/build/include/linux/kconfig.h  \
	-D__KERNEL__ -D__ASM_SYSREG_H -Wno-unused-value -Wno-pointer-sign \
	-Wno-compare-distinct-pointer-types \
	-O2 -emit-llvm -c sampleip_kern.c -o -| llc -march=bpf -filetype=obj -o sampleip_kern.o
 $                                                          #编译内核态程序
 $ sudo ./sampleip_user
 #+END_EXAMPLE

 #+BEGIN_EXAMPLE
 此处的命令由内核编译流程中提取得到
 $ cd ${linux-src-tree}
 $ make menuconfig
 $ make -B -d -n samples/bpf/ > output.txt

 注意当gcc大于6.2时，会出现堆栈指针检查的错误，导致无法编译；此时需要
 低版本的gcc，如gcc-4.9
 $ make CC=gcc-4.9 -B -d -n samples/bpf/ > output.txt
 #+END_EXAMPLE

* xt_bpf
netfilter

* cls_bpf
qdisc layer

* 示例代码阅读
 - TCP/UDP/ICMP报文统计计数， ~samples/bpf/sock_example.c~
    : bpf_create_map()
    :   syscall(__NR_bpf, BPF_MAP_CREATE,,)          ~/kernel/bpf/syscall.c
    : bpf_prog_load()
    :   syscall(__NR_bpf, BPF_PROG_LOAD,,)
    :     bpf_prog_load()                            ~/kernel/bpf/syscall.c
    :       find_prog_type()
    :       bpf_check()                              合法性检测
    :       fixup_bpf_calls()
    :       bpf_prog_select_runtime()                JIT编译
    :       bpf_prog_new_fd()                        建立对应的fd
    : open_raw_sock()
    : setsockopt()                                   ~/net/socket.c
    :   SYSCALL_DEFINE5(setsockopt,,)
    :     sock_setsockopt()
    :       sk_attach_bpf()                          ~/net/core/filter.c
    :         __sk_attach_prog()                     ebpf程序赋值到struct sock->sk_filter
    : bpf_lookup_elem()

* 参考
 - BSD报文过滤器的设计文档，bpf-usenix93.pdf
 - LSF文档，~/Documentation/networking/filter.txt
 - CBPF编译器工具，~/tools/net/
 - man bpf
 - ebpf编程示例，~/samples/bpf/
 - [[https://github.com/iovisor/bcc][BCC]]
 - man tc
 - ~/kernel/bpf/
 - ~/tools/lib/bpf/




