#+TITLE: linux内核插口操控摘录
#+AUTHOR: sqlfocus


本文档摘录linux的插口操作，以期对内核协议栈的了解更加深入，为日后工作中
排出内核问题、性能调优等提供支撑！

* sk_buff
此数据结构贯穿整个网络数据包的处理流程，存放真实数据包的相关信息，做为关
键信息缓存，以加速处理速度。
 - 定义在~/include/linux/skbuff.h
 - 分配/释放alloc_skb()/kfree_skb(), ~/net/core/skbuff.c
 - 设备驱动中分配/释放dev_alloc_skb/dev_kfree_skb(), ~/include/linux/skbuff.h
 - 操控数据区skb_reserve/skb_put/skb_push/skb_pull(), ~/include/linux/skbuff.h
 - 记录IP分片信息struct skb_shared_info, ~/include/linux/skbuff.h

* net_device
存储网络报文相关的网络设备信息。
 - 定义在~/include/linux/netdevice.h

* 初始化流程
一个网络设备可用，就必须被内核认可，并且关联正确的驱动程序；驱动程序把
驱动设备所需的所有信息存储在私有数据结构中，然后与其他需要此设备的内核
组件交互；注册和初始化的一部分由内核负责，其他部分由设备驱动程序负责
 - 硬件初始化       :: 由驱动程序和通用总线层完成
 - 软件初始化       :: 依赖用户配置
 - 功能初始化       :: 依赖网络选项

#+BEGIN_EXAMPLE
内核初始化流程
-start_kernel()                         内核C语言入口，~/init/main.c
  -parse_early_param()
  -parse_args()                         解析参数
  -softirq_init()                       注册软中断, TASKLET_SOFTIRQ/HI_SOFTIRQ
  -rest_init()
    -kernel_thread()                    启动init进程，kernel_init()
      -kernel_init_freeable()
        -do_basic_setup()
          -do_initcalls()
            -do_initcall_level()
              -do_one_initcall()        执行early_initcall/core_initcall()等注册的初始化函数
              -->net_dev_init()         通过 subsys_initcall() 注册，level 4
              -->inet_init()            通过 fs_initcall() 注册，level 5
                -ip_init()              IPv4初始化
                -ipfrag_init()          分片重组系统初始化
                -dev_add_pack()         注册IPv4报文类型，ip_packet_type，包含了L3入口ip_rcv()
#+END_EXAMPLE

** net_dev_init()
流量控制、入口队列初始化，定义在~/net/core/dev.c
#+BEGIN_EXAMPLE
-register_pernet_device(&loopback_net_ops)   注册loopback口
-open_softirq()                              注册软中断，NET_TX_SOFTIRQ/NET_RX_SOFTIRQ
#+END_EXAMPLE

** inet_init()
网络协议栈初始化的过程中，会注册内核支持的域、协议等信息，并设置对应的
操作集合。协议栈初始化入口，定义在~/net/ipv4/af_inet.c文件
  #+BEGIN_EXAMPLE
  -inet_init()                          IPv4协议栈初始化入口，~net/ipv4/af_inet.c
    -proto_register()
      -list_add(, &proto_list)          注册并初始化proto_list链表，如tcp_prot
    -sock_register()
      -rcu_assign_pointer()             注册到net_families[]，如inet_family_ops
    -inet_add_protocol()
      -cmpxchg()                        注册到inet_protos[]，如tcp_protocol
    -inet_register_protosw()
      -list_add_rcu()                   利用inetsw_array[]初始化inetsw[]
    -ip_init()
    -tcp_v4_init()                      ~/net/ipv4/tcp_ipv4.c
      -inet_hashinfo_init()             初始化tcp_hashinfo的监听队列
      -register_pernet_subsys()         注册网络命名空间的操控集tcp_sk_ops
    -tcp_init()                         建立TCP请求的缓存，初始化各种内存限制，~/net/ipv4/tcp.c
    -dev_add_pack()                     注册IPv4对应的l3报文类型
  #+END_EXAMPLE

** ip_init()
此函数初始化IPv4协议栈，定义在~/net/ipv4/ip_output.c
#+BEGIN_EXAMPLE
-ip_init()
  -ip_rt_init()                         路由子系统初始化
  -inet_initpeers()                     管理IP端点的基础系统
  -igmp_mc_init()
#+END_EXAMPLE

** ipfrag_init()
此函数初始化分片重组所需的变量、hash方法等，定义在~/net/ipv4/ip_fragment.c

* 全局变量
** ~dev_boot_setup~
内核引导期间通过参数"netdev="传入的网络接口配置信息，定义在~/net/core/dev.c

** ~inet_protos[]~
此数组定义了内核支持的知名协议，当IP层上送数据时，用于查找并确定正确的四
层接收函数，如 =tcp_protocol= 等
  #+BEGIN_EXAMPLE
  ~/net/ipv4/protocol.c
  const struct net_protocol __rcu *inet_protos[MAX_INET_PROTOS] __read_mostly;
  #+END_EXAMPLE

*** ~tcp_protocol~
  #+BEGIN_EXAMPLE
  ~/net/ipv4/af_inet.c
  static const struct net_protocol tcp_protocol = {
      ...
  };
  #+END_EXAMPLE
    
** ~inetsw[]~
inetsw_array[]是持久的初始化在内核代码中的传输层协议数组；网络初始化过
程中由它初始化inetsw[]数组。

它将原语类型、对应的协议、四层协议操作、插口操作、标识等相关内容关联到
一起，组成一套完成的传输层。
  #+BEGIN_EXAMPLE
  ~/net/ipv4/af_inet.c

  static struct list_head inetsw[SOCK_MAX];
  static struct inet_protosw inetsw_array[] = {
      ...
  };
  #+END_EXAMPLE

** ~irq_desc[]~
硬件中断向量表，定义在~/kernel/irq/irqdesc.c

** ~net_families[]~
此数组定义了内核支持的所有domain - 协议族，如 =AF_UNIX= 对应的等
  #+BEGIN_EXAMPLE
  ~/net/socket.c
  static const struct net_proto_family __rcu *net_families[NPROTO] __read_mostly;
  #+END_EXAMPLE

*** ~inet_family_ops~
  #+BEGIN_EXAMPLE
  AF_INET域，~/net/ipv4/af_inet.c
  static const struct net_proto_family inet_family_ops = {
      ...
  };
  #+END_EXAMPLE

** ~proto_list~
此链表定义了内核支持的所有四层协议的操控接口，如 =tcp_proto= 等
  #+BEGIN_EXAMPLE
  ~/net/core/sock.c
  static LIST_HEAD(proto_list);
  #+END_EXAMPLE

*** ~tcp_prot~
  #+BEGIN_EXAMPLE
  ~/net/ipv4/tcp_ipv4.c
  struct proto tcp_prot = {
     ...
  };
  #+END_EXAMPLE

** ~softirq_vec[]~
软中断向量表，定义在~/kernel/softirq.c

** ~softnet_data~
每CPU队列，存放收到的报文，定义在~/include/linux/netdevice.h

** ~tcp_death_row~
此结构定义了TIMEWAIT插口队列及其参数。
  #+BEGIN_EXAMPLE
  ~/net/ipv4/tcp_minisocks.c

  struct inet_timewait_death_row tcp_death_row = {
      ...
  };
  #+END_EXAMPLE

** ~tcp_hashinfo~
此结构定义了TCP在IPv4中的各种hash队列表，包括bind端口队列、已建立链接的
五元组hash表等。
  #+BEGIN_EXAMPLE
  ~/net/ipv4/tcp_ipv4.c

  struct inet_hashinfo tcp_hashinfo;
  #+END_EXAMPLE

** ~ptype_base/ptype_all~
内核注册的L3报文类型，包括协议值及处理函数等，~/net/core/dev.c

* L2接收
处理L2层帧的函数是由中断事件驱动的
 - 网卡接收到帧，触发中断
 - CPU接收中断，执行do_IRQ()
 - 根据中断表触发驱动程序注册的函数
 - 中断处理函数执行立即性任务
    : 拷贝sk_buff
    : 初始化某些sk_buff参数
    : 调度NET_RX_SOFTIRQ
 - 软中断执行

#+BEGIN_EXAMPLE
中断处理流程
-do_IRQ()                               中断处理入口，~/arch/x86/kernel/irq.c
  -e1000_intr()                         e1000网卡中断处理函数，~/drivers/net/ethernet/intel/e1000/e1000_main.c
    -__napi_schedule()
      -____napi_schedule()
        -list_add_tail()                struct napi_struct->poll_list挂接到struct softnet_data->poll_list
        -__raise_softirq_irqoff()       触发软中断NET_RX_SOFTIRQ
#+END_EXAMPLE
#+BEGIN_EXAMPLE
软中断处理流程
-net_rx_action()                        软中断NET_RX_SOFTIRQ入口，~/net/core/dev.c
  -napi_poll()
    -struct napi_struct->poll()         虚拟poll
    -->process_backlog()                非NAPI通用接口，~/net/core/dev.c
      -__netif_receive_skb()
        -__netif_receive_skb_core()
          -skb_vlan_untag()
          -struct packet_type->func()
          -->ip_rcv()                   L3层处理入口，~/net/ipv4/ip_input.c
    -->e1000_clean()                    e1000的NAPI接口，~/drivers/net/ethernet/intel/e1000/e1000_main.c
      -struct e1000_adapter->clean_rx()
      -->e1000_clean_rx_irq()
        -e1000_receive_skb()
          -napi_gro_receive()
            -napi_skb_finish()
              -netif_receive_skb_internal()
                -__netif_receive_skb()
#+END_EXAMPLE

* 网桥接收
网桥是学术上的名词，交换机是物理设备的名称，它们是对应的。网桥驱动程序
定义在~/net/bridge/br.c

#+BEGIN_EXAMPLE
软中断处理流程
-net_rx_action()                        软中断NET_RX_SOFTIRQ入口，~/net/core/dev.c
  -napi_poll()
    -struct napi_struct->poll()         虚拟poll
    -->process_backlog()                非NAPI通用接口，~/net/core/dev.c
      -__netif_receive_skb()
        -__netif_receive_skb_core()
          -skb_vlan_untag()
          -struct sk_buff->dev->rx_handler()
          -->br_handle_frame()          网桥处理入口，~/net/bridge/br_input.c
            -br_handle_frame_finish()
              ---br_forward()           转发
              ---br_flood()             广播
              ---br_pass_frame_up()     本地接收
                -br_netif_receive_skb()
                  -netif_receive_skb()
                    -netif_receive_skb_internal()
    -->e1000_clean()                    e1000的NAPI接口，~/drivers/net/ethernet/intel/e1000/e1000_main.c
      -struct e1000_adapter->clean_rx()
      -->e1000_clean_rx_irq()
        -e1000_receive_skb()
          -napi_gro_receive()
            -napi_skb_finish()
              -netif_receive_skb_internal()
                -__netif_receive_skb()

#+END_EXAMPLE

* L3接收
3层是网络协议的核心层，涉及邻居系统、路由系统、netfilter点等众多子系统，
关联耦合性、复杂度相比其他都较高。
#+BEGIN_EXAMPLE
-ip_rcv()                           L3层处理入口，~/net/ipv4/ip_input.c
  -ip_rcv_finish()
    -ip_route_input_noref()         查路由，~/net/ipv4/route.c
    -ip_rcv_options()               处理ip选项
    -dst_input()
      -->ip_local_deliver()         上传L4
        -ip_defrag()                分片重组
        -ip_local_deliver_finish()
          -raw_local_deliver()
            -raw_v4_input()         raw类型报文，~/net/ipv4/raw.c
          ---tcp_v4_rcv()           TCP报文, ~/net/ipv4/tcp_ipv4.c
          ---udp_rcv()              UDP报文, ~/net/ipv4/udp.c
          ---icmp_rcv()             ICMP报文, ~/net/ipv4/icmp.c
      -->ip_forward()               转发，~/net/ipv4/ip_forward.c
        -ip_forward_finish()
          -ip_forward_options()     构建ip选项
          -dst_output()
#+END_EXAMPLE

* L3发送
接收L4或者转发报文，并和邻居系统联动，最终发送出去
#+BEGIN_EXAMPLE
此函数一般由TCP、STCP使用，发送报文
-ip_queue_xmit()                    ~/net/ipv4/ip_output.c
  -ip_route_output_ports()          查路由
  -ip_options_build()               构建IP选项
  -ip_select_ident_segs()           设置IP ID
  -ip_local_out()
    -dst_output()
      -->ip_output()                ~/net/ipv4/ip_output.c
        ---ip_fragment()            分段发送
          -ip_do_fragment()
            -ip_finish_output2()
        ---ip_finish_output()       非分段发送
          -ip_finish_output2()
            -dst_neigh_output()     邻居系统#+END_EXAMPLE
#+END_EXAMPLE
#+BEGIN_EXAMPLE
此函数为raw或UDP等使用，发送报文
-ip_append_data()                   缓存数据，待发送，~/net/ipv4/ip_output.c

-ip_push_pending_frames()           发送数据，~/net/ipv4/ip_output.c
  -ip_send_skb()
    -ip_local_out()
      -__ip_local_out()
        -dst_output()
#+END_EXAMPLE

* 分片重组
分片重组是L3 IP层的重要任务之一

#+BEGINE_EXAMPLE
-ip_defrag()                            分片重组入口，~/net/ipv4/ip_fragment.c
#+END_EXAMPLE

#+BEGIN_EXAMPLE
-ip_fragment()                          IP分段入口，~/net/ipv4/ip_output.c
#+END_EXAMPLE

* socket()
应用程序原型， =int socket(int domain, int type, int protocol);= ，建立
通信系统的一端，并返回对应的描述符。

domain指定了通信域，它用来选择用于通信的协议族(protocol family)，包括
=AF_UNIX/AF_INET/AF_INET6/...= 

type字段指定了用于通信的原语，如 =SOCK_STREAM/SOCK_DGRAM/SOCK_RAW/...=

protocol字段指定插口使用的协议，一般情况下在某个通信域内，基于某通信原
语的协议只有一种，此时此字段可以缺省为0；当然，也可能存在多种协议的可
能，此时此字段必须为特定的值。
  #+BEGIN_EXAMPLE
  -SYSCALL_DEFINE3(socket,,,,,)                 入口, ~/net/socket.c
    1-sock_create()                             创建插口结构，并初始化
      -__sock_create()
        -sock_alloc()
          -this_cpu_add(sockets_in_use, 1)      分配struct socket，增加插口计数
        -net_families[]->create()
        -->inet_create()                        调用对应domain的创建流程, 以AF_INET为例, ~/net/ipv4/af_inet.c
          -sk_alloc()                           分配struct sock
          -sock_init_data()
            -sk_set_socket()                    建立socket和sock的关联
          -struct sock->sk_prot->init()
          -->tcp_prot->init()                   特定协议的信息初始化
          -->tcp_v4_init_sock()
            -tcp_init_sock()
    1-sock_map_fd()                             创建文件描述符，并关联
  #+END_EXAMPLE

* bind()
  #+BEGIN_EXAMPLE
  -SYSCALL_DEFINE3(bind,,,,,)                   bind()入口，~/net/socket.c
    -struct socket->ops->bind()
    -->inet_stream_ops->bind()
    -->inet_bind()                              TCP绑定入口，~/net/ipv4/af_inet.c
      -struct sock->sk_prot->bind()             TCP为NULL
      -赋值struct inet_sock->inet_rcv_saddr     本地监听地址
      -赋值->inet_saddr                         发送时，本端地址
      -struct sock->sk_prot->get_port()
      -->tcp_prot->get_port()
      -->inet_csk_get_port()                    验证绑定有效性，获取绑定端口，inet_connection_sock.c
      -赋值struct inet_sock->inet_sport         发送时，本地源端口
  #+END_EXAMPLE

** 端口绑定算法
检测插口选用的端口是否冲突 
 1. Sockets bound to different interfaces may share a local port.
    Failing that, goto test 2;
      : 不同接口可共享端口
 2. If all sockets have ~sk->sk_reuse~ set, and none of them are in
    ~TCP_LISTEN~ state, the port may be shared.
    Failing that, goto test 3;
      : 相同接口，但都设置了地址重用(~SO_REUSEADDR~)，且都不在 ~TCP_LISTEN~ 状态
 3. If all sockets are bound to a specific ~inet_sk(sk)->rcv_saddr~ local
    address, and none of them are the same, the port may be
    shared;
      : 相同接口，未设置端口重用，但绑定到不同的本地地址
 4. Failing this, the port cannot be shared.
 
* listen()
  #+BEGIN_EXAMPLE
  -SYSCALL_DEFINE2(listen,,,,)                   listen()入口，~/net/socket.c
    -参数backlog限制, 不大于net.core.somaxconn
    -struct socket->ops->listen()
    -->inet_stream_ops->listen()
    -->inet_listen()                             SOCK_STREAM原语的监听，~/net/ipv4/af_inet.c
      -inet_csk_listen_start()
      -...(简化调用层级)
      -                                          情形1: 加入tcp_prot->h.hashinfo->ehash[]
        -inet_ehash_nolisten()
      -                                          情形2: 加入tcp_prot->h.hashinfo->listening_hash[]
        -hlist_add_head_rcu()
        -sock_prot_inuse_add()
  #+END_EXAMPLE

* DONE accept()
  CLOSED: [2016-11-28 Mon 10:54]
本出只摘录了accept()系统调用的表面处理流程，即从ACCEPT队列获取已完成
三次握手的协议插口；而ACCEPT队列形成所对应的底层三次握手流程未涉猎。
  #+BEGIN_EXAMPLE
  -SYSCALL_DEFINE3(accept,,,,,,)                 accept()入口，~/net/socket.c
    -sys_accept4()
      -sock_alloc()                              分配BSD层插口
      -get_unused_fd_flags()                     分配未使用的fd描述符
      -sock_alloc_file()                         分配对应的文件
      -struct socket->ops->accept()              BSD插口层操控函数
      -->inet_stream_ops->accept()
      -->inet_accept()
        -struct sock->sk_prot->accept()          特定于协议的操控函数
        -->tcp_prot->accept()
        -->inet_csk_accept()
          -reqsk_queue_remove()                  从ACCEPT队列获取完成三次握手的插口
      -fd_install()                              建立fd和file的对应关系
  #+END_EXAMPLE

* DONE connect()
  CLOSED: [2016-11-28 Mon 10:07]
此处仅仅是脉络式摘录，代码中关于路由、报文构造等也未注解，仅关注TCP、插
口状态机变更；待后续遇到问题，以问题驱动进一步注解。

  #+BEGIN_EXAMPLE
  -SYSCALL_DEFINE3(connect,,,,,,)               connect()入口，~/net/socket.c
    -struct socket->ops->connect()
    -->inet_stream_ops->connect()
    -->inet_stream_connect()
      -__inet_stream_connect()                  干实事儿的入口，~/net/ipv4/af_inet.c
        -struct sock->sk_prot->connect
        -->tcp_prot->connect()
        -->tcp_v4_connect()                     发起链接请求，~/net/ipv4/tcp_ipv4.c
          -tcp_connect()                        构建并发送SYN报文
        -inet_wait_for_connect()                等待建立链接
        -设置struct socket->state = SS_CONNECTED
  #+END_EXAMPLE

* TODO 三次握手
ab

* TODO 快速打开fastopen
ab

* SO_REUSEPORT
SO_REUSEPORT属性在linux内核3.9之后才提供，使得同一主机上多个插口可以绑定到
相同的端口，而且内核提供负载均衡策略，从而优化并提高并发服务器的性能。

** SO_REUSEPORT提升性能?
运行在Linux系统上网络应用程序，为了利用多核的优势，一般使用多进程/多线程服
务器模型：
 - 单线程listen+accept，其他多线程接收分发任务
     : CPU的工作负载不再是问题
     : 但仍有其他瓶颈
     :    1) 单线程listener，处理高速率海量连接时，会成为瓶颈
     :    2) CPU缓存行miss套接字结构(socket structure)现象严重
 - 所有工作线程都accept()在同一个服务器套接字上
     : 多线程访问server socket锁竞争严重
     : 高负载下，线程之间处理不均衡；导致核数增加，性能并没有提升
     : 导致CPU缓存行跳跃(cache line bouncing)
     : 繁忙CPU存在较大延迟

** SO_REUSEPORT原理
The new socket option allows multiple sockets on the same host to bind 
to the same port, and is intended to improve the performance of 
multithreaded network server applications running on top of multicore 
systems.

SO_REUSEPORT支持多个进程或者线程绑定到同一端口，提高服务器程序的性能，解决
了以下问题：
  - 允许多个套接字bind()/listen()同一个TCP/UDP端口
  - 每一个线程拥有自己的服务器套接字
  - 在服务器套接字上没有了锁的竞争
  - 内核层面实现负载均衡
  - 安全层面，监听同一个端口的套接字只能位于同一个用户下面

** nginx配置
  #+BEGIN_EXAMPLE
  events {
      accept_mutex off;
  }

  http {
     server {
         listen 80 reuseport;
     }
  }
  #+END_EXAMPLE

** 内核实现
linux核心的实现主要有三点：
  - 扩展socket option
      : 增加SO_REUSEPORT选项
  - 修改bind系统调用实现
      : 支持可以绑定到相同的IP和端口
  - 修改处理新建连接的实现
      : 查找listener时，在监听相同IP和端口的多个sock之间均衡选择

*** setsockopt()
  #+BEGIN_EXAMPLE
  -SYSCALL_DEFINE5(setsockopt,,,,,,)                   入口，~/net/socket.c
    -sock_setsockopt()
      -设置struct socket->sk->sk_reuseport             =0/1, 设置插口属性值，~/net/core/sock.c
  #+END_EXAMPLE

*** bind()
ab

*** listen()
ab

*** accept()
ab

** 参考
  - [[http://www.blogjava.net/yongboy/archive/2015/02/12/422893.html?utm_source=tuicool&utm_medium=referral][SO_REUSEPORT学习笔记]]
  - [[http://m.blog.chinaunix.net/uid-10167808-id-3807060.html][多个进程绑定相同端口的实现分析]]

* 新名词
 - NAPI         :: new API, 网络层新接口，糅合了poll/中断两种报文接收模式
   : 如果接收到新帧时，内核还没有完成处理前几个帧的工作，驱动程序就没有必
   : 要产生其他中断事件；然后当该队列为空时再重新开启中断功能

